plugins {
    alias libs.plugins.android.application apply false
    alias libs.plugins.jetbrains.kotlin.android apply false
    alias libs.plugins.jetbrains.kotlin.plugin.compose apply false
    alias libs.plugins.jlleitschuh.gradle.ktlint apply false
    alias libs.plugins.google.services apply false
    alias libs.plugins.firebase.crashlytics apply false
    alias libs.plugins.version.catalog.update
}

apply from: "variables.gradle"

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

tasks.register('clean', Delete) {
    delete(layout.buildDirectory)
}