org.gradle.jvmargs=-Xmx1536m
android.useAndroidX=true
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=true
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.dependency.excludeLibraryComponentsFromConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
android.builtInKotlin=false
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE,FLAT_DIR_REPOSITORY_USED,LIBRARY_CONSTRAINTS_SHOULD_BE_DISABLED,OBSOLETE_API
android.newDsl=false
